# Generated by Django 4.1 on 2024-01-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YearlyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("pujigat", models.FloatField(blank=True, default=0)),
                ("chalugat", models.FloatField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UjuriGunaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("gunaso_petika", models.PositiveIntegerField(blank=True, default=0)),
                ("gunaso_adhikari", models.PositiveIntegerField(blank=True, default=0)),
                ("zilla", models.PositiveIntegerField(blank=True, default=0)),
                ("banijya", models.PositiveIntegerField(blank=True, default=0)),
                ("patra", models.PositiveIntegerField(blank=True, default=0)),
                ("akhtiyar", models.PositiveIntegerField(blank=True, default=0)),
                ("patrakar", models.PositiveIntegerField(blank=True, default=0)),
                ("sarkar", models.PositiveIntegerField(blank=True, default=0)),
                ("upavokta", models.PositiveIntegerField(blank=True, default=0)),
                ("others", models.PositiveIntegerField(blank=True, default=0)),
                ("jamma", models.PositiveIntegerField(blank=True, default=0)),
                ("sambodhan", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UdyogSifaris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("milk", models.PositiveIntegerField(blank=True, default=0)),
                ("oil", models.PositiveIntegerField(blank=True, default=0)),
                ("fruits", models.PositiveIntegerField(blank=True, default=0)),
                ("spice", models.PositiveIntegerField(blank=True, default=0)),
                ("tea", models.PositiveIntegerField(blank=True, default=0)),
                ("salt", models.PositiveIntegerField(blank=True, default=0)),
                ("khadanna", models.PositiveIntegerField(blank=True, default=0)),
                ("water", models.PositiveIntegerField(blank=True, default=0)),
                ("sweets", models.PositiveIntegerField(blank=True, default=0)),
                ("confectionery", models.PositiveIntegerField(blank=True, default=0)),
                ("meat", models.PositiveIntegerField(blank=True, default=0)),
                ("grain", models.PositiveIntegerField(blank=True, default=0)),
                ("others", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rajaswo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("rajaswo_collected", models.FloatField(blank=True, default=0)),
                (
                    "month_or_quarter",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "वैशाख"),
                            (2, "जेठ"),
                            (3, "असार"),
                            (4, "साउन"),
                            (5, "भदौ"),
                            (6, "असोज"),
                            (7, "कार्तिक"),
                            (8, "मंसिर"),
                            (9, "पुष"),
                            (10, "माघ"),
                            (11, "फागुन"),
                            (12, "चैत"),
                        ]
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuarterelyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("pujigat", models.FloatField(blank=True, default=0)),
                ("chalugat", models.FloatField(blank=True, default=0)),
                (
                    "month_or_quarter",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "First"),
                            (2, "Second"),
                            (2, "Third"),
                            (4, "Forth"),
                        ]
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrayogsalaBisleysan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("milk", "दुध तथा दुध पदार्थ"),
                            ("oil", "तेल तथा घिउ जन्य"),
                            ("fruits", "फल तथा सागपात"),
                            ("spice", "मसला"),
                            ("tea", "चिया, कफि"),
                            ("salt", "नुन"),
                            ("khadanna", "खाद्यान्न दलहन र सोवाट बनेका"),
                            ("water", "प्र. पिउने पानी"),
                            ("sweets", "गुलियो पदार्थ"),
                            ("confectionery", "कन्फेक्सनरी"),
                            ("meat", "मासु तथा मासुजन्य"),
                            ("grain", "दाना"),
                            ("others", "अन्य"),
                        ],
                        max_length=100,
                    ),
                ),
                ("b_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("b_pratikul", models.PositiveIntegerField(blank=True, default=0)),
                ("u_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("u_pratikul", models.PositiveIntegerField(blank=True, default=0)),
                ("ay_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("ay_pratikul", models.PositiveIntegerField(blank=True, default=0)),
                ("v_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("v_pratikul", models.PositiveIntegerField(blank=True, default=0)),
                ("k_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("k_pratikul", models.PositiveIntegerField(blank=True, default=0)),
                ("a_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("a_pratikul", models.PositiveIntegerField(blank=True, default=0)),
                ("kul_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("kul_pratikul", models.PositiveIntegerField(blank=True, default=0)),
                ("sample", models.PositiveIntegerField(blank=True, default=0)),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PragatiBibaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "months",
                    models.CharField(
                        blank=True,
                        choices=[
                            (1, "वैशाख"),
                            (2, "जेठ"),
                            (3, "असार"),
                            (4, "साउन"),
                            (5, "भदौ"),
                            (6, "असोज"),
                            (7, "कार्तिक"),
                            (8, "मंसिर"),
                            (9, "पुष"),
                            (10, "माघ"),
                            (11, "फागुन"),
                            (12, "चैत"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "kharcha_type",
                    models.CharField(
                        blank=True,
                        choices=[("P", "पुँजीगत"), ("C", "चालु")],
                        max_length=10,
                    ),
                ),
                ("upasirshak", models.CharField(blank=True, default="", max_length=50)),
                ("karya", models.CharField(blank=True, default="", max_length=255)),
                (
                    "ekai",
                    models.CharField(
                        blank=True,
                        choices=[("S", "संख्या"), ("P", "पटक")],
                        max_length=10,
                    ),
                ),
                ("b_lakshya", models.PositiveIntegerField(blank=True, default=0)),
                ("m_parinam", models.PositiveIntegerField(blank=True, default=0)),
                ("t_lakshya", models.PositiveIntegerField(blank=True, default=0)),
                ("t_pragati", models.PositiveIntegerField(blank=True, default=0)),
                ("t_pratisat", models.FloatField(blank=True, default=0)),
                ("h_pragati", models.PositiveIntegerField(blank=True, default=0)),
                ("h_pratisat", models.FloatField(blank=True, default=0)),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatraNabikaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("milk", models.PositiveIntegerField(blank=True, default=0)),
                ("oil", models.PositiveIntegerField(blank=True, default=0)),
                ("fruits", models.PositiveIntegerField(blank=True, default=0)),
                ("spice", models.PositiveIntegerField(blank=True, default=0)),
                ("tea", models.PositiveIntegerField(blank=True, default=0)),
                ("salt", models.PositiveIntegerField(blank=True, default=0)),
                ("khadanna", models.PositiveIntegerField(blank=True, default=0)),
                ("water", models.PositiveIntegerField(blank=True, default=0)),
                ("sweets", models.PositiveIntegerField(blank=True, default=0)),
                ("confectionery", models.PositiveIntegerField(blank=True, default=0)),
                ("meat", models.PositiveIntegerField(blank=True, default=0)),
                ("grain", models.PositiveIntegerField(blank=True, default=0)),
                ("others", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatraJari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("milk", models.PositiveIntegerField(blank=True, default=0)),
                ("oil", models.PositiveIntegerField(blank=True, default=0)),
                ("fruits", models.PositiveIntegerField(blank=True, default=0)),
                ("spice", models.PositiveIntegerField(blank=True, default=0)),
                ("tea", models.PositiveIntegerField(blank=True, default=0)),
                ("salt", models.PositiveIntegerField(blank=True, default=0)),
                ("khadanna", models.PositiveIntegerField(blank=True, default=0)),
                ("water", models.PositiveIntegerField(blank=True, default=0)),
                ("sweets", models.PositiveIntegerField(blank=True, default=0)),
                ("confectionery", models.PositiveIntegerField(blank=True, default=0)),
                ("meat", models.PositiveIntegerField(blank=True, default=0)),
                ("grain", models.PositiveIntegerField(blank=True, default=0)),
                ("others", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NamunaBisleysan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("milk", "दुध तथा दुध पदार्थ"),
                            ("oil", "तेल तथा घिउ जन्य"),
                            ("fruits", "फल तथा सागपात"),
                            ("spice", "मसला"),
                            ("tea", "चिया, कफि"),
                            ("salt", "नुन"),
                            ("khadanna", "खाद्यान्न दलहन र सोवाट बनेका"),
                            ("water", "प्र. पिउने पानी"),
                            ("sweets", "गुलियो पदार्थ"),
                            ("confectionery", "कन्फेक्सनरी"),
                            ("meat", "मासु तथा मासुजन्य"),
                            ("grain", "दाना"),
                            ("others", "अन्य"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "ekai",
                    models.CharField(
                        blank=True,
                        choices=[("S", "संख्या"), ("P", "पटक")],
                        max_length=10,
                    ),
                ),
                ("lakshya", models.PositiveIntegerField(blank=True, default=0)),
                ("pragati1", models.PositiveIntegerField(blank=True, default=0)),
                ("mahina_pragati", models.PositiveIntegerField(blank=True, default=0)),
                ("sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("parameter", models.PositiveIntegerField(blank=True, default=0)),
                ("pragati2", models.PositiveIntegerField(blank=True, default=0)),
                ("pratisat", models.FloatField(blank=True, default=0)),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NamunaBibaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("milk", models.PositiveIntegerField(blank=True, default=0)),
                ("oil", models.PositiveIntegerField(blank=True, default=0)),
                ("fruits", models.PositiveIntegerField(blank=True, default=0)),
                ("spice", models.PositiveIntegerField(blank=True, default=0)),
                ("tea", models.PositiveIntegerField(blank=True, default=0)),
                ("salt", models.PositiveIntegerField(blank=True, default=0)),
                ("khadanna", models.PositiveIntegerField(blank=True, default=0)),
                ("water", models.PositiveIntegerField(blank=True, default=0)),
                ("sweets", models.PositiveIntegerField(blank=True, default=0)),
                ("confectionery", models.PositiveIntegerField(blank=True, default=0)),
                ("meat", models.PositiveIntegerField(blank=True, default=0)),
                ("grain", models.PositiveIntegerField(blank=True, default=0)),
                ("others", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("pujigat", models.FloatField(blank=True, default=0)),
                ("chalugat", models.FloatField(blank=True, default=0)),
                ("new_field", models.CharField(max_length=200, null=True)),
                (
                    "month_or_quarter",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "वैशाख"),
                            (2, "जेठ"),
                            (3, "असार"),
                            (4, "साउन"),
                            (5, "भदौ"),
                            (6, "असोज"),
                            (7, "कार्तिक"),
                            (8, "मंसिर"),
                            (9, "पुष"),
                            (10, "माघ"),
                            (11, "फागुन"),
                            (12, "चैत"),
                        ]
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Logobitaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("green", "हरियो स्टिकर"),
                            ("yellow1", "पेहेलोमा एउटा रातो धर्सो"),
                            ("yellow2", "पेहेलोमा दुइटा रातो धर्सो"),
                            ("red", "रातो स्टिकर"),
                        ],
                        max_length=50,
                    ),
                ),
                ("c_pragati", models.PositiveIntegerField(blank=True, default=0)),
                ("h_pragati1", models.PositiveIntegerField(blank=True, default=0)),
                ("h_pragati2", models.PositiveIntegerField(blank=True, default=0)),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KhadyaPrasodhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "miti",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("naam", models.CharField(blank=True, default="", max_length=255)),
                ("sthan", models.CharField(blank=True, default="", max_length=255)),
                ("m_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("p_sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("nikaya", models.TextField(blank=True, default="")),
                ("bisaya", models.TextField(blank=True, default="")),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailUdyog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "samuha",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "दूध तथा दुग्ध पदार्थहरु"),
                            ("B", "तेल तथा घउि"),
                            ("C", "फल तथा सागपात पदार्थहरु"),
                            ("D", "मसला पदार्थहरु"),
                            ("E", "चिया, कफि कोका तथा सो बाट बनेका पदार्थहरु"),
                            ("F", "नुन"),
                            ("G", "खाद्यान्न दलहन तथा सो बाट बनेका पदार्थहरु"),
                            ("H", "प्याक गरएिको पउिने पानी"),
                            ("I", "गुलियो पदार्थ"),
                            ("J", "कन्फेक्सनरी"),
                            ("K", "आहारपुरक"),
                            ("L", "ईनर्जी ड्रिंक"),
                            ("M", "बालआहार"),
                            ("N", "विविध"),
                        ],
                        max_length=10,
                    ),
                ),
                ("naam", models.CharField(blank=True, default="", max_length=255)),
                ("thegana", models.CharField(blank=True, default="", max_length=255)),
                ("byakti", models.CharField(blank=True, default="", max_length=255)),
                ("samparka", models.CharField(blank=True, default="", max_length=15)),
                ("jilla", models.CharField(blank=True, default="", max_length=255)),
                ("mukhya", models.CharField(blank=True, default="", max_length=255)),
                ("brand", models.CharField(blank=True, default="", max_length=255)),
                ("karyalaya", models.CharField(blank=True, default="", max_length=255)),
                (
                    "j_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                (
                    "n_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailRenew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "samuha",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "दूध तथा दुग्ध पदार्थहरु"),
                            ("B", "तेल तथा घउि"),
                            ("C", "फल तथा सागपात पदार्थहरु"),
                            ("D", "मसला पदार्थहरु"),
                            ("E", "चिया, कफि कोका तथा सो बाट बनेका पदार्थहरु"),
                            ("F", "नुन"),
                            ("G", "खाद्यान्न दलहन तथा सो बाट बनेका पदार्थहरु"),
                            ("H", "प्याक गरएिको पउिने पानी"),
                            ("I", "गुलियो पदार्थ"),
                            ("J", "कन्फेक्सनरी"),
                            ("K", "आहारपुरक"),
                            ("L", "ईनर्जी ड्रिंक"),
                            ("M", "बालआहार"),
                            ("N", "विविध"),
                        ],
                        max_length=10,
                    ),
                ),
                ("naam", models.CharField(blank=True, default="", max_length=255)),
                ("thegana", models.CharField(blank=True, default="", max_length=255)),
                ("byakti", models.CharField(blank=True, default="", max_length=255)),
                ("samparka", models.CharField(blank=True, default="", max_length=15)),
                ("jilla", models.CharField(blank=True, default="", max_length=255)),
                ("mukhya", models.CharField(blank=True, default="", max_length=255)),
                ("brand", models.CharField(blank=True, default="", max_length=255)),
                ("karyalaya", models.CharField(blank=True, default="", max_length=255)),
                (
                    "j_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                (
                    "n_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "samuha",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "दूध तथा दुग्ध पदार्थहरु"),
                            ("B", "तेल तथा घउि"),
                            ("C", "फल तथा सागपात पदार्थहरु"),
                            ("D", "मसला पदार्थहरु"),
                            ("E", "चिया, कफि कोका तथा सो बाट बनेका पदार्थहरु"),
                            ("F", "नुन"),
                            ("G", "खाद्यान्न दलहन तथा सो बाट बनेका पदार्थहरु"),
                            ("H", "प्याक गरएिको पउिने पानी"),
                            ("I", "गुलियो पदार्थ"),
                            ("J", "कन्फेक्सनरी"),
                            ("K", "आहारपुरक"),
                            ("L", "ईनर्जी ड्रिंक"),
                            ("M", "बालआहार"),
                            ("N", "विविध"),
                        ],
                        max_length=10,
                    ),
                ),
                ("naam", models.CharField(blank=True, default="", max_length=255)),
                ("thegana", models.CharField(blank=True, default="", max_length=255)),
                ("byakti", models.CharField(blank=True, default="", max_length=255)),
                ("samparka", models.CharField(blank=True, default="", max_length=15)),
                ("jilla", models.CharField(blank=True, default="", max_length=255)),
                ("mukhya", models.CharField(blank=True, default="", max_length=255)),
                ("brand", models.CharField(blank=True, default="", max_length=255)),
                ("karyalaya", models.CharField(blank=True, default="", max_length=255)),
                (
                    "j_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                (
                    "n_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailRbpa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                (
                    "related_month",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "वैशाख"),
                            (2, "जेठ"),
                            (3, "असार"),
                            (4, "साउन"),
                            (5, "भदौ"),
                            (6, "असोज"),
                            (7, "कार्तिक"),
                            (8, "मंसिर"),
                            (9, "पुष"),
                            (10, "माघ"),
                            (11, "फागुन"),
                            (12, "चैत"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "broad_type",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Fruits"), (2, "Vegetables")],
                        default=0,
                    ),
                ),
                ("country1", models.CharField(blank=True, default="", max_length=255)),
                ("sample1", models.PositiveIntegerField(blank=True, default=0)),
                ("quantity1", models.PositiveIntegerField(blank=True, default=0)),
                ("sample2", models.PositiveIntegerField(blank=True, default=0)),
                ("quantity2", models.PositiveIntegerField(blank=True, default=0)),
                ("country2", models.CharField(blank=True, default="", max_length=255)),
                ("sample3", models.PositiveIntegerField(blank=True, default=0)),
                ("quantity3", models.PositiveIntegerField(blank=True, default=0)),
                ("country3", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailMudha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("naam", models.CharField(blank=True, default="", max_length=255)),
                ("b_naam", models.CharField(blank=True, default="", max_length=255)),
                (
                    "n_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("n_sthan", models.CharField(blank=True, default="", max_length=255)),
                ("n_khani", models.CharField(blank=True, default="", max_length=255)),
                (
                    "p_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                (
                    "b_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("prakar", models.CharField(blank=True, default="", max_length=255)),
                ("parameter", models.CharField(blank=True, default="", max_length=255)),
                ("m_sthan", models.CharField(blank=True, default="", max_length=255)),
                (
                    "m_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("m_khani", models.CharField(blank=True, default="", max_length=255)),
                ("karyalaya", models.CharField(blank=True, default="", max_length=255)),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("naam", models.CharField(blank=True, default="", max_length=255)),
                (
                    "logo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "अति उत्तम"),
                            ("B", "उत्तम"),
                            ("C", "संतोषजनक"),
                            ("D", "सामान्य"),
                            ("E", "स्तरकिरणमा नपरेको"),
                        ],
                        max_length=10,
                    ),
                ),
                ("thegana", models.CharField(blank=True, default="", max_length=255)),
                ("samparka", models.CharField(blank=True, default="", max_length=255)),
                ("jilla", models.CharField(blank=True, default="", max_length=255)),
                (
                    "j_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                (
                    "n_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("karyalaya", models.CharField(blank=True, default="", max_length=255)),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailGunaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "p_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                (
                    "srot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "गुनासो पेटीका"),
                            ("B", "गुनासो अधिकारी समक्ष"),
                            ("C", "जिल्ला प्रशासन कार्यालयबाट लेखिआएको"),
                            ("D", "बाणिज्य कार्यालयबाट लेखिआएको"),
                            ("E", "पत्र पत्रिका"),
                            ("F", "अख्तियार दु. अ.आ."),
                            ("G", "पत्रकार"),
                            ("H", "हेलो सरकार"),
                            ("I", "उपभोक्ता संघ संस्था"),
                            ("J", "अन्य"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "s_miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("bibaran", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailAnugaman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "nirichad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("B", "बजार/पसल"),
                            ("K", "खाद्य उद्योग"),
                            ("H", "होटल, रेष्टुरेण्ट, मिठाई पसल"),
                            ("S", "संयुक्त अनुगमन"),
                            ("D", "दाना उद्योग"),
                            ("A", "अन्य"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "miti",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        validators=[main.validators.validate_nepali_date],
                    ),
                ),
                ("naam", models.CharField(blank=True, default="", max_length=255)),
                ("thegana", models.CharField(blank=True, default="", max_length=255)),
                ("nikaya", models.CharField(blank=True, default="", max_length=255)),
                ("a_bibaran", models.CharField(blank=True, default="", max_length=255)),
                ("silbandi", models.CharField(blank=True, default="", max_length=255)),
                ("parinam", models.CharField(blank=True, default="", max_length=255)),
                ("mulya", models.CharField(blank=True, default="", max_length=255)),
                ("nirdesan", models.CharField(blank=True, default="", max_length=255)),
                ("d_bibaran", models.CharField(blank=True, default="", max_length=255)),
                ("kaifiyat", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BarsikLakshya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("namuna_bibaran", models.PositiveIntegerField(blank=True, default=0)),
                ("anugaman", models.PositiveIntegerField(blank=True, default=0)),
                ("logo", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "namuna_bisleysan",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("prayogsala", models.PositiveIntegerField(blank=True, default=0)),
                ("patrajari", models.PositiveIntegerField(blank=True, default=0)),
                ("patranabikaran", models.PositiveIntegerField(blank=True, default=0)),
                ("udyog_sifaris", models.PositiveIntegerField(blank=True, default=0)),
                ("aayat_niryat", models.PositiveIntegerField(blank=True, default=0)),
                ("ujuri_gunaso", models.PositiveIntegerField(blank=True, default=0)),
                ("rbpr", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnugamanBibaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("udyog", "उद्योग"),
                            ("pasal", "पसल"),
                            ("supermarket", "सुपरमार्केट"),
                            ("godam", "गोदाम"),
                            ("hotel", "होटल, रेस्टुरेन्ट, मिठाई पसल आदी"),
                            ("dana", "दाना पदार्थ"),
                            ("anya", "अन्य"),
                        ],
                        max_length=100,
                    ),
                ),
                ("patak", models.PositiveIntegerField(blank=True, default=0)),
                ("sankhya", models.PositiveIntegerField(blank=True, default=0)),
                ("pragati", models.PositiveIntegerField(blank=True, default=0)),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AayatNiryat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_on_np_date",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "broad_type",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Import"),
                            (2, "Export"),
                            (3, "Bhansar Chali/Nikasi"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "related_month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "वैशाख"),
                            (2, "जेठ"),
                            (3, "असार"),
                            (4, "साउन"),
                            (5, "भदौ"),
                            (6, "असोज"),
                            (7, "कार्तिक"),
                            (8, "मंसिर"),
                            (9, "पुष"),
                            (10, "माघ"),
                            (11, "फागुन"),
                            (12, "चैत"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("milk", "दुध तथा दुध पदार्थ"),
                            ("oil", "तेल तथा घिउ जन्य"),
                            ("fruits", "फल तथा सागपात"),
                            ("spice", "मसला"),
                            ("tea", "चिया, कफि"),
                            ("salt", "नुन"),
                            ("khadanna", "खाद्यान्न दलहन र सोवाट बनेका"),
                            ("water", "प्र. पिउने पानी"),
                            ("sweets", "गुलियो पदार्थ"),
                            ("confectionery", "कन्फेक्सनरी"),
                            ("meat", "मासु तथा मासुजन्य"),
                            ("grain", "दाना"),
                            ("others", "अन्य"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "ekai",
                    models.CharField(
                        blank=True,
                        choices=[("S", "संख्या"), ("P", "पटक")],
                        max_length=10,
                    ),
                ),
                ("m_pragati", models.PositiveIntegerField(blank=True, default=0)),
                ("pratikul_n", models.PositiveIntegerField(blank=True, default=0)),
                ("pratikul_p", models.PositiveIntegerField(blank=True, default=0)),
                ("countries_count", models.PositiveIntegerField(default=0, null=True)),
                ("countries_names", models.CharField(max_length=1000, null=True)),
                ("kaifiyat", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
