# Generated by Django 4.1 on 2024-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AarthikBarsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aarthik_barsa", models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name="monthlyexpense",
            name="aarthik_barsa",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="quarterelybudget",
            name="aarthik_barsa",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="yearlybudget",
            name="aarthik_barsa",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
