# Generated by Django 4.1 on 2024-01-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_aarthikbarsa_monthlyexpense_aarthik_barsa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyexpense",
            name="aarthik_barsa",
            field=models.CharField(default="80/81", max_length=12),
        ),
        migrations.AlterField(
            model_name="quarterelybudget",
            name="aarthik_barsa",
            field=models.CharField(default="80/81", max_length=12),
        ),
        migrations.AlterField(
            model_name="yearlybudget",
            name="aarthik_barsa",
            field=models.CharField(default="80/81", max_length=12),
        ),
    ]
