# Generated by Django 4.1 on 2024-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_monthlyexpense_aarthik_barsa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyexpense",
            name="new_field",
        ),
        migrations.AlterField(
            model_name="quarterelybudget",
            name="month_or_quarter",
            field=models.PositiveIntegerField(
                choices=[(1, "First"), (2, "Second"), (3, "Third"), (4, "Fourth")]
            ),
        ),
    ]
